### PR TITLE
Log errors during LESS compilation

### PR DESCRIPTION
**Pull request by okalex**
As referenced in https://github.com/kitajchuk/node-squarespace-server/issues/98, this doesn't fix the issue, but at least improves visibility of problems during the compilation step.

### CODE REVIEW

**Comment by kitajchuk** [comment]
This looks good and is a good idea. Not to be too much of a stickler, but if you can change the `error == null` condition to `error === null` and add a semicolon to the end of the log line I'll merge this :)

**Comment by okalex** [comment]
Ah of course. Been a little while since I've worked on javascript ;) Done.

**Comment by kitajchuk** [comment]
Sweet, looks great :)

**Comment by kitajchuk** [comment]
Bumped patch version and published 0.2.7 - https://www.npmjs.com/package/node-squarespace-server

**Pull request merged**
